'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class apiTasks
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("AeonLabs.MainTestApp.apiTasks", GetType(apiTasks).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 2.
        '''</summary>
        Friend Shared ReadOnly Property addons() As String
            Get
                Return ResourceManager.GetString("addons", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 7.
        '''</summary>
        Friend Shared ReadOnly Property attendance() As String
            Get
                Return ResourceManager.GetString("attendance", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 8.
        '''</summary>
        Friend Shared ReadOnly Property attendanceAnnotations() As String
            Get
                Return ResourceManager.GetString("attendanceAnnotations", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 5.
        '''</summary>
        Friend Shared ReadOnly Property attendanceRecords() As String
            Get
                Return ResourceManager.GetString("attendanceRecords", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 9.
        '''</summary>
        Friend Shared ReadOnly Property holidays() As String
            Get
                Return ResourceManager.GetString("holidays", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 25.
        '''</summary>
        Friend Shared ReadOnly Property journal() As String
            Get
                Return ResourceManager.GetString("journal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 23.
        '''</summary>
        Friend Shared ReadOnly Property journalattendance() As String
            Get
                Return ResourceManager.GetString("journalattendance", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 24.
        '''</summary>
        Friend Shared ReadOnly Property journalLog() As String
            Get
                Return ResourceManager.GetString("journalLog", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1.
        '''</summary>
        Friend Shared ReadOnly Property login() As String
            Get
                Return ResourceManager.GetString("login", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 13.
        '''</summary>
        Friend Shared ReadOnly Property mobileDevices() As String
            Get
                Return ResourceManager.GetString("mobileDevices", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 20.
        '''</summary>
        Friend Shared ReadOnly Property photos() As String
            Get
                Return ResourceManager.GetString("photos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 6.
        '''</summary>
        Friend Shared ReadOnly Property queries() As String
            Get
                Return ResourceManager.GetString("queries", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 14.
        '''</summary>
        Friend Shared ReadOnly Property site() As String
            Get
                Return ResourceManager.GetString("site", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 19.
        '''</summary>
        Friend Shared ReadOnly Property siteActivitiesMap() As String
            Get
                Return ResourceManager.GetString("siteActivitiesMap", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 32.
        '''</summary>
        Friend Shared ReadOnly Property siteActivitiesMapEdit() As String
            Get
                Return ResourceManager.GetString("siteActivitiesMapEdit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 3.
        '''</summary>
        Friend Shared ReadOnly Property siteClosedDays() As String
            Get
                Return ResourceManager.GetString("siteClosedDays", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 21.
        '''</summary>
        Friend Shared ReadOnly Property siteDailyProduction() As String
            Get
                Return ResourceManager.GetString("siteDailyProduction", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 16.
        '''</summary>
        Friend Shared ReadOnly Property siteGeneralContractors() As String
            Get
                Return ResourceManager.GetString("siteGeneralContractors", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 15.
        '''</summary>
        Friend Shared ReadOnly Property siteManagers() As String
            Get
                Return ResourceManager.GetString("siteManagers", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 22.
        '''</summary>
        Friend Shared ReadOnly Property siteMaterialsDelivery() As String
            Get
                Return ResourceManager.GetString("siteMaterialsDelivery", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 12.
        '''</summary>
        Friend Shared ReadOnly Property siteMaterialsReception() As String
            Get
                Return ResourceManager.GetString("siteMaterialsReception", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 17.
        '''</summary>
        Friend Shared ReadOnly Property siteSections() As String
            Get
                Return ResourceManager.GetString("siteSections", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 18.
        '''</summary>
        Friend Shared ReadOnly Property siteTeams() As String
            Get
                Return ResourceManager.GetString("siteTeams", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1050.
        '''</summary>
        Friend Shared ReadOnly Property templateFiles() As String
            Get
                Return ResourceManager.GetString("templateFiles", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 4.
        '''</summary>
        Friend Shared ReadOnly Property unscheduledWorks() As String
            Get
                Return ResourceManager.GetString("unscheduledWorks", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 31.
        '''</summary>
        Friend Shared ReadOnly Property userProfile() As String
            Get
                Return ResourceManager.GetString("userProfile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 10.
        '''</summary>
        Friend Shared ReadOnly Property workerAbsenses() As String
            Get
                Return ResourceManager.GetString("workerAbsenses", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 11.
        '''</summary>
        Friend Shared ReadOnly Property workerClothes() As String
            Get
                Return ResourceManager.GetString("workerClothes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 28.
        '''</summary>
        Friend Shared ReadOnly Property workerDossier() As String
            Get
                Return ResourceManager.GetString("workerDossier", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 29.
        '''</summary>
        Friend Shared ReadOnly Property workerLimosas() As String
            Get
                Return ResourceManager.GetString("workerLimosas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 27.
        '''</summary>
        Friend Shared ReadOnly Property workerLocate() As String
            Get
                Return ResourceManager.GetString("workerLocate", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
